name: Kenny Se
favicon: null
layout_spectrum: 0.6059577420819551
typography_spectrum: 0.8630727923009545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0037022854667156935
  lightness: 0.7160315152723342
  saturation: 0.8103105921763927
  rhythmicContrast: 0.861501447390765
purpose: []
